name: Test
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  run:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['5.3', '5.4', '5.5']
    name: PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        run: |
          version=${{ matrix.php-versions }}
          bash install.sh ${version/./}
      - name: Testing PHP version
        run: |
          php -v
          php -r "if(strpos(phpversion(), '${{ matrix.php-versions }}') === false) {throw new Exception('Wrong PHP version Installed');}"
      - name: Testing
        run: |
          php -m