name: Test
on:
  repository_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  run:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['5.3', '5.4', '5.5']
    name: PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        run: |
          zstd --version
          version=${{ matrix.php-versions }}
          bash install.sh ${version/./}
      - name: Testing PHP version
        run: |
          php --ini
          php -v
          phpize --version
          php-config --version
          php -r "if(strpos(phpversion(), '${{ matrix.php-versions }}') === false) {throw new Exception('Wrong PHP version Installed');}"
      - name: Testing PHP extensions
        run: |
          php -m
          version=${{ matrix.php-versions }}
          for bin in /tmp/php"${version/./}"/ext/*.so; do
            extension=$(basename "$bin" | cut -d'.' -f 1)
            ([ "$extension" != "xdebug" ] && php -r "if(! extension_loaded('$extension')) {throw new Exception('$extension not found');}") &
            to_wait+=( $! )
          done
          wait "${to_wait[@]}"
          php -r "if(! extension_loaded('Zend OPcache')) {throw new Exception('Zend OPcache not found');}"
      - name: Testing PECL version
        run: pecl -V
      - name: Testing SSL in file_get_contents
        run: php -r "echo file_get_contents('https://repo.packagist.org/packages.json');"